name: nian_common_utils
description: "念安科技-通用工具包"
version: 0.0.1
homepage: "https://github.com/Aquarius-M/nian_common_utils"
repository: "https://github.com/Aquarius-M/nian_common_utils"


environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  # 权限
  permission_handler: ^11.3.1
  # 持久化储存
  synchronized: ^3.1.0+1
  shared_preferences: ^2.2.2
  # 包，设备信息
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  network_info_plus: ^5.0.3

  path: ^1.9.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

  # 通知
  flutter_local_notifications: ^17.0.0

  # 文件
  mime: ^1.0.5

  # 图片
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_cropper: ^5.0.1
  # wechat_assets_picker:
  # wechat_camera_picker:
  flutter_image_compress: ^2.2.0
  image_gallery_saver: ^2.0.3

  flutter_easyloading: ^3.0.5

  date_format: ^2.0.7

  fluttertoast: ^8.2.4

  dio: ^5.4.2+1
  connectivity_plus: ^6.0.2

  get_server: ^1.2.1
  logger: ^2.2.0

  # 加解密
  crypto: ^3.0.3
  convert: ^3.1.1

  # 数据库
  sqflite: ^2.3.3

  # 应用内通知
  in_app_notification: ^1.1.2
  flutter_ringtone_player: ^4.0.0+2

  # 引导
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.nian.plugin.nian_common_utils
        pluginClass: NianCommonUtilsPlugin
      ios:
        pluginClass: NianCommonUtilsPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
